<?xml version="1.0"?>
<package format="3">
  <name>mcl_localization_lab</name>
  <version>0.0.1</version>
  <description>Monte Carlo Localization lab package with a known map and Gazebo world.</description>
  <maintainer email="a01541805@tec.mx">Cesar Mateo Sanchez Alvarez</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
